// packages/vue/demo/src/App.vue
<script setup lang="ts">
import { Cropper } from '@ldesign/cropper-vue'
import { ref } from 'vue'
// import '@ldesign/cropper-vue/es/style.css'

const cropperRef = ref()
const croppedImage = ref('')

function onReady() {
  console.log('✅ Cropper ready!')
}

function onCrop(event: CustomEvent) {
  console.log('📐 Crop data:', event.detail)
}

function rotate() {
  cropperRef.value?.rotate(90)
}

function flipH() {
  const data = cropperRef.value?.getData()
  if (data) {
    cropperRef.value?.scale(-(data.scaleX || 1), undefined)
  }
}

function flipV() {
  const data = cropperRef.value?.getData()
  if (data) {
    cropperRef.value?.scale(undefined, -(data.scaleY || 1))
  }
}

function reset() {
  cropperRef.value?.reset()
  croppedImage.value = ''
}

function getCropped() {
  const canvas = cropperRef.value?.getCroppedCanvas()
  if (canvas) {
    croppedImage.value = canvas.toDataURL()
  }
}
</script>

<template>
  <div class="app">
    <h1>🖼️ Cropper Vue 3 Demo</h1>

    <div class="controls">
      <button @click="rotate">
        ↻ Rotate
      </button>
      <button @click="flipH">
        ↔ Flip H
      </button>
      <button @click="flipV">
        ↕ Flip V
      </button>
      <button @click="reset">
        Reset
      </button>
      <button @click="getCropped">
        Get Cropped Image
      </button>
    </div>

    <Cropper
      ref="cropperRef"
      src="https://picsum.photos/1200/800"
      :aspect-ratio="16 / 9"
      :view-mode="1"
      drag-mode="crop"
      :auto-crop="true"
      class="cropper-wrapper"
      @ready="onReady"
      @crop="onCrop"
    />

    <div v-if="croppedImage" class="result">
      <h3>Cropped Result:</h3>
      <img :src="croppedImage" alt="Cropped" style="max-width: 400px; border: 2px solid #ccc;">
    </div>
  </div>
</template>

<style scoped>
.app {
  max-width: 1200px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
}

.controls {
  display: flex;
  gap: 10px;
  justify-content: center;
  margin: 20px 0;
}

.cropper-wrapper {
  width: 800px;
  height: 600px;
  margin: 0 auto;
  border: 2px solid #646cff;
  border-radius: 8px;
  overflow: hidden;
}

.result {
  margin-top: 20px;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #1a1a1a;
  cursor: pointer;
  transition: border-color 0.25s;
  color: white;
}

button:hover {
  border-color: #646cff;
}
</style>

// packages/react/demo/src/App.tsx
import { useRef, useState } from 'react'
import { Cropper, type CropperRef } from '@ldesign/cropper-react'
// import '@ldesign/cropper-react/es/style.css'
import './App.css'

function App() {
  const cropperRef = useRef<CropperRef>(null)
  const [croppedImage, setCroppedImage] = useState('')

  const handleReady = () => {
    console.log('✅ Cropper ready!')
  }

  const handleCrop = (e: CustomEvent) => {
    console.log('📐 Crop data:', e.detail)
  }

  const rotate = () => {
    cropperRef.current?.rotate(90)
  }

  const flipH = () => {
    const data = cropperRef.current?.getData()
    if (data) {
      cropperRef.current?.scale(-(data.scaleX || 1), undefined)
    }
  }

  const flipV = () => {
    const data = cropperRef.current?.getData()
    if (data) {
      cropperRef.current?.scale(undefined, -(data.scaleY || 1))
    }
  }

  const reset = () => {
    cropperRef.current?.reset()
    setCroppedImage('')
  }

  const getCropped = () => {
    const canvas = cropperRef.current?.getCroppedCanvas()
    if (canvas) {
      setCroppedImage(canvas.toDataURL())
    }
  }

  return (
    <div className="app">
      <h1>🖼️ Cropper React Demo</h1>

      <div className="controls">
        <button onClick={rotate}>↻ Rotate</button>
        <button onClick={flipH}>↔ Flip H</button>
        <button onClick={flipV}>↕ Flip V</button>
        <button onClick={reset}>Reset</button>
        <button onClick={getCropped}>Get Cropped Image</button>
      </div>

      <Cropper
        ref={cropperRef}
        src="https://picsum.photos/1200/800"
        aspectRatio={16 / 9}
        viewMode={1}
        dragMode="crop"
        autoCrop={true}
        onReady={handleReady}
        onCrop={handleCrop}
        style={{ width: '800px', height: '600px', margin: '0 auto' }}
        className="cropper-wrapper"
      />

      {croppedImage && (
        <div className="result">
          <h3>Cropped Result:</h3>
          <img src={croppedImage} alt="Cropped" style={{ maxWidth: '400px', border: '2px solid #ccc' }} />
        </div>
      )}
    </div>
  )
}

export default App
