// packages/angular/es/cropper.component.js
/*!
 * ***********************************
 * @ldesign/cropper-angular v2.0.0 *
 * Built with rollup               *
 * Build time: 2024-10-29 10:23:42 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */
import { __decorate, __metadata } from 'tslib';
import { ViewChild, ElementRef, Input, Output, Component, ViewEncapsulation, EventEmitter } from '@angular/core';
import { Cropper } from '@ldesign/cropper-core';

let CropperComponent = class CropperComponent {
    constructor() {
        Object.defineProperty(this, "containerRef", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "src", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "aspectRatio", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "viewMode", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "dragMode", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "options", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        Object.defineProperty(this, "ready", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: new EventEmitter()
        });
        Object.defineProperty(this, "cropstart", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: new EventEmitter()
        });
        Object.defineProperty(this, "cropmove", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: new EventEmitter()
        });
        Object.defineProperty(this, "cropend", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: new EventEmitter()
        });
        Object.defineProperty(this, "crop", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: new EventEmitter()
        });
        Object.defineProperty(this, "zoom", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: new EventEmitter()
        });
        Object.defineProperty(this, "cropper", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
    }
    ngOnInit() {
        this.initCropper();
    }
    ngOnDestroy() {
        this.cropper?.destroy();
    }
    initCropper() {
        const options = {
            ...this.options,
            src: this.src,
            aspectRatio: this.aspectRatio,
            viewMode: this.viewMode,
            dragMode: this.dragMode,
            ready: (e) => this.ready.emit(e),
            cropstart: (e) => this.cropstart.emit(e),
            cropmove: (e) => this.cropmove.emit(e),
            cropend: (e) => this.cropend.emit(e),
            crop: (e) => this.crop.emit(e),
            zoom: (e) => this.zoom.emit(e)
        };
        this.cropper = new Cropper(this.containerRef.nativeElement, options);
    }
    // Public API methods
    getCroppedCanvas(options) {
        return this.cropper?.getCroppedCanvas(options) ?? null;
    }
    getCropBoxData() {
        return this.cropper?.getCropBoxData() ?? null;
    }
    getImageData() {
        return this.cropper?.getImageData() ?? null;
    }
    setAspectRatio(aspectRatio) {
        this.cropper?.setAspectRatio(aspectRatio);
    }
    reset() {
        this.cropper?.reset();
    }
    clear() {
        this.cropper?.clear();
    }
    replace(url) {
        this.cropper?.replace(url);
    }
    destroy() {
        this.cropper?.destroy();
    }
    zoom(ratio) {
        this.cropper?.zoom(ratio);
    }
    rotate(degree) {
        this.cropper?.rotate(degree);
    }
    scale(scaleX, scaleY) {
        this.cropper?.scale(scaleX, scaleY);
    }
    move(offsetX, offsetY) {
        this.cropper?.move(offsetX, offsetY);
    }
};
__decorate([
    ViewChild('cropperContainer', { static: true }),
    __metadata("design:type", ElementRef)
], CropperComponent.prototype, "containerRef", void 0);
__decorate([
    Input(),
    __metadata("design:type", String)
], CropperComponent.prototype, "src", void 0);
__decorate([
    Input(),
    __metadata("design:type", Number)
], CropperComponent.prototype, "aspectRatio", void 0);
__decorate([
    Input(),
    __metadata("design:type", Number)
], CropperComponent.prototype, "viewMode", void 0);
__decorate([
    Input(),
    __metadata("design:type", String)
], CropperComponent.prototype, "dragMode", void 0);
__decorate([
    Input(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "options", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "ready", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "cropstart", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "cropmove", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "cropend", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "crop", void 0);
__decorate([
    Output(),
    __metadata("design:type", Object)
], CropperComponent.prototype, "zoom", void 0);
CropperComponent = __decorate([
    Component({
        selector: 'l-cropper',
        standalone: true,
        template: `<div #cropperContainer class="cropper-container"></div>`,
        styleUrls: ['./cropper.component.css'],
        encapsulation: ViewEncapsulation.None
    })
], CropperComponent);

export { CropperComponent };
/*! End of @ldesign/cropper-angular | Powered by @ldesign/builder */
//# sourceMappingURL=cropper.component.js.map

// packages/react/es/Cropper.js
/*!
 * ***********************************
 * @ldesign/cropper-react v2.0.0   *
 * Built with rollup               *
 * Build time: 2024-10-29 10:32:02 *
 * Build mode: production          *
 * Minified: No                    *
 * ***********************************
 */
import { jsx } from 'react/jsx-runtime';
import { forwardRef, useRef, useEffect, useImperativeHandle } from 'react';
import { Cropper as Cropper$1 } from '@ldesign/cropper-core';
import '@ldesign/cropper-core/style.css';

const Cropper = forwardRef((props, ref) => {
  const { onReady, onCropStart, onCropMove, onCropEnd, onCrop, onZoom, style, className, ...cropperOptions } = props;
  const containerRef = useRef(null);
  const cropperRef = useRef(null);
  useEffect(() => {
    if (!containerRef.current)
      return;
    const options = {
      ...cropperOptions,
      ready: (e) => {
        onReady?.(e);
        if (cropperOptions.ready)
          cropperOptions.ready(e);
      },
      cropstart: (e) => {
        onCropStart?.(e);
        if (cropperOptions.cropstart)
          cropperOptions.cropstart(e);
      },
      cropmove: (e) => {
        onCropMove?.(e);
        if (cropperOptions.cropmove)
          cropperOptions.cropmove(e);
      },
      cropend: (e) => {
        onCropEnd?.(e);
        if (cropperOptions.cropend)
          cropperOptions.cropend(e);
      },
      crop: (e) => {
        onCrop?.(e);
        if (cropperOptions.crop)
          cropperOptions.crop(e);
      },
      zoom: (e) => {
        onZoom?.(e);
        if (cropperOptions.zoom)
          cropperOptions.zoom(e);
      }
    };
    cropperRef.current = new Cropper$1(containerRef.current, options);
    return () => {
      cropperRef.current?.destroy();
      cropperRef.current = null;
    };
  }, []);
  useEffect(() => {
    if (props.src && cropperRef.current) {
      cropperRef.current.replace(props.src);
    }
  }, [props.src]);
  useImperativeHandle(ref, () => ({
    getCropper: () => cropperRef.current,
    getCropBoxData: () => cropperRef.current?.getCropBoxData() || null,
    setCropBoxData: (data) => {
      cropperRef.current?.setCropBoxData(data);
    },
    getData: (rounded) => cropperRef.current?.getData(rounded) || null,
    getCroppedCanvas: (options) => cropperRef.current?.getCroppedCanvas(options) || null,
    replace: async (src) => {
      await cropperRef.current?.replace(src);
    },
    reset: () => cropperRef.current?.reset(),
    clear: () => cropperRef.current?.clear(),
    rotate: (degree) => cropperRef.current?.rotate(degree),
    scale: (scaleX, scaleY) => cropperRef.current?.scale(scaleX, scaleY),
    move: (offsetX, offsetY) => cropperRef.current?.move(offsetX, offsetY),
    zoom: (ratio) => cropperRef.current?.zoom(ratio),
    enable: () => cropperRef.current?.enable(),
    disable: () => cropperRef.current?.disable(),
    destroy: () => {
      cropperRef.current?.destroy();
      cropperRef.current = null;
    }
  }));
  return jsx("div", { ref: containerRef, className: `cropper-container ${className || ""}`, style });
});
Cropper.displayName = "Cropper";

export { Cropper, Cropper as default };
/*! End of @ldesign/cropper-react | Powered by @ldesign/builder */
//# sourceMappingURL=Cropper.js.map
