// packages/angular/src/cropper.component.ts
import type {
  ElementRef,
  OnDestroy,
  OnInit,
} from '@angular/core'
import type { CropBoxData, CropperOptions, ImageData } from '@ldesign/cropper-core'
import {
  Component,
  EventEmitter,
  Input,
  Output,
  ViewChild,
  ViewEncapsulation,
} from '@angular/core'
import { Cropper as CropperCore } from '@ldesign/cropper-core'

@Component({
  selector: 'l-cropper',
  standalone: true,
  template: `<div #cropperContainer class="cropper-container"></div>`,
  styleUrls: ['./cropper.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class CropperComponent implements OnInit, OnDestroy {
  @ViewChild('cropperContainer', { static: true }) containerRef!: ElementRef<HTMLDivElement>

  @Input() src?: string
  @Input() aspectRatio?: number
  @Input() viewMode?: 0 | 1 | 2 | 3
  @Input() dragMode?: 'crop' | 'move' | 'none'
  @Input() options?: CropperOptions

  @Output() ready = new EventEmitter<CustomEvent>()
  @Output() cropstart = new EventEmitter<CustomEvent>()
  @Output() cropmove = new EventEmitter<CustomEvent>()
  @Output() cropend = new EventEmitter<CustomEvent>()
  @Output() crop = new EventEmitter<CustomEvent>()
  @Output() zoom = new EventEmitter<CustomEvent>()

  private cropper?: CropperCore

  ngOnInit(): void {
    this.initCropper()
  }

  ngOnDestroy(): void {
    this.cropper?.destroy()
  }

  private initCropper(): void {
    const options: CropperOptions = {
      ...this.options,
      src: this.src,
      aspectRatio: this.aspectRatio,
      viewMode: this.viewMode,
      dragMode: this.dragMode,
      ready: e => this.ready.emit(e),
      cropstart: e => this.cropstart.emit(e),
      cropmove: e => this.cropmove.emit(e),
      cropend: e => this.cropend.emit(e),
      crop: e => this.crop.emit(e),
      zoom: e => this.zoom.emit(e),
    }

    this.cropper = new CropperCore(this.containerRef.nativeElement, options)
  }

  // Public API methods
  getCroppedCanvas(options?: any): HTMLCanvasElement | null {
    return this.cropper?.getCroppedCanvas(options) ?? null
  }

  getCropBoxData(): CropBoxData | null {
    return this.cropper?.getCropBoxData() ?? null
  }

  getImageData(): ImageData | null {
    return this.cropper?.getImageData() ?? null
  }

  setAspectRatio(aspectRatio: number): void {
    this.cropper?.setAspectRatio(aspectRatio)
  }

  reset(): void {
    this.cropper?.reset()
  }

  clear(): void {
    this.cropper?.clear()
  }

  replace(url: string): void {
    this.cropper?.replace(url)
  }

  destroy(): void {
    this.cropper?.destroy()
  }

  zoom(ratio: number): void {
    this.cropper?.zoom(ratio)
  }

  rotate(degree: number): void {
    this.cropper?.rotate(degree)
  }

  scale(scaleX: number, scaleY?: number): void {
    this.cropper?.scale(scaleX, scaleY)
  }

  move(offsetX: number, offsetY?: number): void {
    this.cropper?.move(offsetX, offsetY)
  }
}

// packages/svelte/src/Cropper.svelte
<script lang="ts">
  import { onMount, onDestroy, createEventDispatcher } from 'svelte'
  import { Cropper as CropperCore, type CropperOptions } from '@ldesign/cropper-core'

  export let src: string | undefined = undefined
  export let aspectRatio: number | undefined = undefined
  export let viewMode: 0 | 1 | 2 | 3 | undefined = undefined
  export let dragMode: 'crop' | 'move' | 'none' | undefined = undefined
  export let options: CropperOptions | undefined = undefined

  const dispatch = createEventDispatcher()
  
  let container: HTMLDivElement
  let cropper: CropperCore | undefined

  onMount(() => {
    if (container) {
      const cropperOptions: CropperOptions = {
        ...options,
        src,
        aspectRatio,
        viewMode,
        dragMode,
        ready: (e) => dispatch('ready', e),
        cropstart: (e) => dispatch('cropstart', e),
        cropmove: (e) => dispatch('cropmove', e),
        cropend: (e) => dispatch('cropend', e),
        crop: (e) => dispatch('crop', e),
        zoom: (e) => dispatch('zoom', e)
      }

      cropper = new CropperCore(container, cropperOptions)
    }
  })

  onDestroy(() => {
    cropper?.destroy()
  })

  // Reactive updates
  $: if (cropper && aspectRatio !== undefined) {
    cropper.setAspectRatio(aspectRatio)
  }

  $: if (cropper && src) {
    cropper.replace(src)
  }

  // Public API methods
  export function getCroppedCanvas(canvasOptions?: any) {
    return cropper?.getCroppedCanvas(canvasOptions)
  }

  export function getCropBoxData() {
    return cropper?.getCropBoxData()
  }

  export function getImageData() {
    return cropper?.getImageData()
  }

  export function setAspectRatio(ratio: number) {
    cropper?.setAspectRatio(ratio)
  }

  export function reset() {
    cropper?.reset()
  }

  export function clear() {
    cropper?.clear()
  }

  export function replace(url: string) {
    cropper?.replace(url)
  }

  export function destroy() {
    cropper?.destroy()
  }

  export function zoom(ratio: number) {
    cropper?.zoom(ratio)
  }

  export function rotate(degree: number) {
    cropper?.rotate(degree)
  }

  export function scale(scaleX: number, scaleY?: number) {
    cropper?.scale(scaleX, scaleY)
  }

  export function move(offsetX: number, offsetY?: number) {
    cropper?.move(offsetX, offsetY)
  }
</script>

<div bind:this={container} class="cropper-container" {...$$restProps}>
  <slot />
</div>

<style>
  .cropper-container {
    width: 100%;
    height: 100%;
    min-height: 400px;
  }
</style>
