// packages/vue/src/Cropper.vue
<template>
  <div ref="containerRef" class="cropper-container"></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, computed } from 'vue'
import { Cropper as CropperCore, type CropperOptions } from '@ldesign/cropper-core'
import type { CropBoxData, CropData } from '@ldesign/cropper-core'

export interface CropperProps extends CropperOptions {
  modelValue?: string
}

const props = withDefaults(defineProps<CropperProps>(), {
  aspectRatio: NaN,
  viewMode: 0,
  dragMode: 'crop',
  responsive: true,
  restore: true,
  checkCrossOrigin: true,
  checkOrientation: true,
  modal: true,
  guides: true,
  center: true,
  highlight: true,
  background: true,
  autoCrop: true,
  movable: true,
  rotatable: true,
  scalable: true,
  zoomable: true,
  zoomOnTouch: true,
  zoomOnWheel: true,
  wheelZoomRatio: 0.1,
  cropBoxMovable: true,
  cropBoxResizable: true,
  toggleDragModeOnDblclick: true
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  ready: [event: CustomEvent]
  cropstart: [event: CustomEvent]
  cropmove: [event: CustomEvent]
  cropend: [event: CustomEvent]
  crop: [event: CustomEvent]
  zoom: [event: CustomEvent]
}>()

const containerRef = ref<HTMLElement>()
let cropperInstance: CropperCore | null = null

// 初始化裁剪器
const initCropper = async () => {
  if (!containerRef.value) return

  const options: CropperOptions = {
    ...props,
    ready: (e) => {
      emit('ready', e)
      if (props.ready) props.ready(e)
    },
    cropstart: (e) => {
      emit('cropstart', e)
      if (props.cropstart) props.cropstart(e)
    },
    cropmove: (e) => {
      emit('cropmove', e)
      if (props.cropmove) props.cropmove(e)
    },
    cropend: (e) => {
      emit('cropend', e)
      if (props.cropend) props.cropend(e)
    },
    crop: (e) => {
      emit('crop', e)
      if (props.crop) props.crop(e)
    },
    zoom: (e) => {
      emit('zoom', e)
      if (props.zoom) props.zoom(e)
    }
  }

  cropperInstance = new CropperCore(containerRef.value, options)
}

// 暴露方法给父组件
const getCropper = () => cropperInstance

const getCropBoxData = (): CropBoxData | null => {
  return cropperInstance?.getCropBoxData() || null
}

const setCropBoxData = (data: Partial<CropBoxData>) => {
  cropperInstance?.setCropBoxData(data)
}

const getData = (rounded?: boolean): CropData | null => {
  return cropperInstance?.getData(rounded) || null
}

const getCroppedCanvas = (options?: any) => {
  return cropperInstance?.getCroppedCanvas(options) || null
}

const replace = async (src: string) => {
  await cropperInstance?.replace(src)
  emit('update:modelValue', src)
}

const reset = () => {
  cropperInstance?.reset()
}

const clear = () => {
  cropperInstance?.clear()
}

const rotate = (degree: number) => {
  cropperInstance?.rotate(degree)
}

const scale = (scaleX: number, scaleY?: number) => {
  cropperInstance?.scale(scaleX, scaleY)
}

const move = (offsetX: number, offsetY?: number) => {
  cropperInstance?.move(offsetX, offsetY)
}

const zoom = (ratio: number) => {
  cropperInstance?.zoom(ratio)
}

const enable = () => {
  cropperInstance?.enable()
}

const disable = () => {
  cropperInstance?.disable()
}

const destroy = () => {
  cropperInstance?.destroy()
  cropperInstance = null
}

// 监听 src 变化
watch(
  () => props.src,
  (newSrc) => {
    if (newSrc && cropperInstance) {
      replace(newSrc)
    }
  }
)

// 监听 modelValue 变化
watch(
  () => props.modelValue,
  (newValue) => {
    if (newValue && cropperInstance && newValue !== props.src) {
      replace(newValue)
    }
  }
)

onMounted(() => {
  initCropper()
})

onBeforeUnmount(() => {
  destroy()
})

// 暴露方法
defineExpose({
  getCropper,
  getCropBoxData,
  setCropBoxData,
  getData,
  getCroppedCanvas,
  replace,
  reset,
  clear,
  rotate,
  scale,
  move,
  zoom,
  enable,
  disable,
  destroy
})
</script>

<style>
@import '@ldesign/cropper-core/style.css';
</style>

// packages/react/src/Cropper.tsx
import type { CropBoxData, CropData, Cropper as CropperCore, type CropperOptions } from '@ldesign/cropper-core'

import React, { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import '@ldesign/cropper-core/style.css'

export interface CropperProps extends CropperOptions {
  onReady?: (event: CustomEvent) => void
  onCropStart?: (event: CustomEvent) => void
  onCropMove?: (event: CustomEvent) => void
  onCropEnd?: (event: CustomEvent) => void
  onCrop?: (event: CustomEvent) => void
  onZoom?: (event: CustomEvent) => void
  style?: React.CSSProperties
  className?: string
}

export interface CropperRef {
  getCropper: () => CropperCore | null
  getCropBoxData: () => CropBoxData | null
  setCropBoxData: (data: Partial<CropBoxData>) => void
  getData: (rounded?: boolean) => CropData | null
  getCroppedCanvas: (options?: any) => HTMLCanvasElement | null
  replace: (src: string) => Promise<void>
  reset: () => void
  clear: () => void
  rotate: (degree: number) => void
  scale: (scaleX: number, scaleY?: number) => void
  move: (offsetX: number, offsetY?: number) => void
  zoom: (ratio: number) => void
  enable: () => void
  disable: () => void
  destroy: () => void
}

export const Cropper = forwardRef<CropperRef, CropperProps>((props, ref) => {
  const {
    onReady,
    onCropStart,
    onCropMove,
    onCropEnd,
    onCrop,
    onZoom,
    style,
    className,
    ...cropperOptions
  } = props

  const containerRef = useRef<HTMLDivElement>(null)
  const cropperRef = useRef<CropperCore | null>(null)

  // 初始化 Cropper
  useEffect(() => {
    if (!containerRef.current)
      return

    const options: CropperOptions = {
      ...cropperOptions,
      ready: (e) => {
        onReady?.(e)
        if (cropperOptions.ready)
          cropperOptions.ready(e)
      },
      cropstart: (e) => {
        onCropStart?.(e)
        if (cropperOptions.cropstart)
          cropperOptions.cropstart(e)
      },
      cropmove: (e) => {
        onCropMove?.(e)
        if (cropperOptions.cropmove)
          cropperOptions.cropmove(e)
      },
      cropend: (e) => {
        onCropEnd?.(e)
        if (cropperOptions.cropend)
          cropperOptions.cropend(e)
      },
      crop: (e) => {
        onCrop?.(e)
        if (cropperOptions.crop)
          cropperOptions.crop(e)
      },
      zoom: (e) => {
        onZoom?.(e)
        if (cropperOptions.zoom)
          cropperOptions.zoom(e)
      },
    }

    cropperRef.current = new CropperCore(containerRef.current, options)

    return () => {
      cropperRef.current?.destroy()
      cropperRef.current = null
    }
  }, [])

  // 监听 src 变化
  useEffect(() => {
    if (props.src && cropperRef.current) {
      cropperRef.current.replace(props.src)
    }
  }, [props.src])

  // 暴露方法
  useImperativeHandle(ref, () => ({
    getCropper: () => cropperRef.current,
    getCropBoxData: () => cropperRef.current?.getCropBoxData() || null,
    setCropBoxData: (data: Partial<CropBoxData>) => {
      cropperRef.current?.setCropBoxData(data)
    },
    getData: (rounded?: boolean) => cropperRef.current?.getData(rounded) || null,
    getCroppedCanvas: (options?: any) => cropperRef.current?.getCroppedCanvas(options) || null,
    replace: async (src: string) => {
      await cropperRef.current?.replace(src)
    },
    reset: () => cropperRef.current?.reset(),
    clear: () => cropperRef.current?.clear(),
    rotate: (degree: number) => cropperRef.current?.rotate(degree),
    scale: (scaleX: number, scaleY?: number) => cropperRef.current?.scale(scaleX, scaleY),
    move: (offsetX: number, offsetY?: number) => cropperRef.current?.move(offsetX, offsetY),
    zoom: (ratio: number) => cropperRef.current?.zoom(ratio),
    enable: () => cropperRef.current?.enable(),
    disable: () => cropperRef.current?.disable(),
    destroy: () => {
      cropperRef.current?.destroy()
      cropperRef.current = null
    },
  }))

  return (
    <div
      ref={containerRef}
      className={`cropper-container ${className || ''}`}
      style={style}
    />
  )
})

Cropper.displayName = 'Cropper'

export default Cropper
