// packages/qwik/src/cropper.tsx
import type { PropFunction } from '@builder.io/qwik'
import type { CropperOptions } from '@ldesign/cropper-core'
import { component$, useSignal, useVisibleTask$ } from '@builder.io/qwik'
import { Cropper as CropperCore } from '@ldesign/cropper-core'

export interface CropperProps {
  src?: string
  aspectRatio?: number
  viewMode?: 0 | 1 | 2 | 3
  dragMode?: 'crop' | 'move' | 'none'
  options?: CropperOptions
  onReady$?: PropFunction<(event: CustomEvent) => void>
  onCropstart$?: PropFunction<(event: CustomEvent) => void>
  onCropmove$?: PropFunction<(event: CustomEvent) => void>
  onCropend$?: PropFunction<(event: CustomEvent) => void>
  onCrop$?: PropFunction<(event: CustomEvent) => void>
  onZoom$?: PropFunction<(event: CustomEvent) => void>
  class?: string
}

export const Cropper = component$<CropperProps>((props) => {
  const containerRef = useSignal<HTMLDivElement>()
  const cropperRef = useSignal<CropperCore>()

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track, cleanup }) => {
    track(() => props.src)
    track(() => props.aspectRatio)

    if (containerRef.value) {
      if (cropperRef.value) {
        // Update existing cropper
        if (props.aspectRatio !== undefined) {
          cropperRef.value.setAspectRatio(props.aspectRatio)
        }
        if (props.src) {
          cropperRef.value.replace(props.src)
        }
      }
      else {
        // Initialize cropper
        const options: CropperOptions = {
          ...props.options,
          src: props.src,
          aspectRatio: props.aspectRatio,
          viewMode: props.viewMode,
          dragMode: props.dragMode,
          ready: e => props.onReady$?.(e),
          cropstart: e => props.onCropstart$?.(e),
          cropmove: e => props.onCropmove$?.(e),
          cropend: e => props.onCropend$?.(e),
          crop: e => props.onCrop$?.(e),
          zoom: e => props.onZoom$?.(e),
        }

        cropperRef.value = new CropperCore(containerRef.value, options)
      }
    }

    cleanup(() => {
      cropperRef.value?.destroy()
      cropperRef.value = undefined
    })
  })

  return (
    <div
      ref={containerRef}
      class={`cropper-container ${props.class || ''}`}
      style={{
        width: '100%',
        height: '100%',
        minHeight: '400px',
      }}
    />
  )
})

// Composable hook for advanced usage
export function useCropper() {
  const cropper = useSignal<CropperCore>()

  const initCropper = (element: HTMLElement, options: CropperOptions) => {
    const instance = new CropperCore(element, options)
    cropper.value = instance
    return instance
  }

  const destroyCropper = () => {
    cropper.value?.destroy()
    cropper.value = undefined
  }

  return {
    cropper,
    initCropper,
    destroyCropper,
  }
}

// packages/solid/src/Cropper.tsx
import type { CropperOptions } from '@ldesign/cropper-core'
import type { Component, JSX } from 'solid-js'
import { Cropper as CropperCore } from '@ldesign/cropper-core'
import { createEffect, createSignal, onCleanup, onMount } from 'solid-js'

export interface CropperProps {
  src?: string
  aspectRatio?: number
  viewMode?: 0 | 1 | 2 | 3
  dragMode?: 'crop' | 'move' | 'none'
  options?: CropperOptions
  onReady?: (event: CustomEvent) => void
  onCropstart?: (event: CustomEvent) => void
  onCropmove?: (event: CustomEvent) => void
  onCropend?: (event: CustomEvent) => void
  onCrop?: (event: CustomEvent) => void
  onZoom?: (event: CustomEvent) => void
  class?: string
  style?: JSX.CSSProperties
}

export const Cropper: Component<CropperProps> = (props) => {
  let containerRef: HTMLDivElement | undefined
  let cropper: CropperCore | undefined
  const [isReady, setIsReady] = createSignal(false)

  onMount(() => {
    if (containerRef) {
      const options: CropperOptions = {
        ...props.options,
        src: props.src,
        aspectRatio: props.aspectRatio,
        viewMode: props.viewMode,
        dragMode: props.dragMode,
        ready: (e) => {
          setIsReady(true)
          props.onReady?.(e)
        },
        cropstart: props.onCropstart,
        cropmove: props.onCropmove,
        cropend: props.onCropend,
        crop: props.onCrop,
        zoom: props.onZoom,
      }

      cropper = new CropperCore(containerRef, options)
    }
  })

  createEffect(() => {
    if (cropper && props.aspectRatio !== undefined) {
      cropper.setAspectRatio(props.aspectRatio)
    }
  })

  createEffect(() => {
    if (cropper && props.src) {
      cropper.replace(props.src)
    }
  })

  onCleanup(() => {
    cropper?.destroy()
  })

  return (
    <div
      ref={containerRef}
      class={props.class}
      style={{
        'width': '100%',
        'height': '100%',
        'min-height': '400px',
        ...props.style,
      }}
    />
  )
}

// Export composable for advanced usage
export function useCropper() {
  const [cropper, setCropper] = createSignal<CropperCore | undefined>()

  const initCropper = (element: HTMLElement, options: CropperOptions) => {
    const instance = new CropperCore(element, options)
    setCropper(instance)
    return instance
  }

  const destroyCropper = () => {
    cropper()?.destroy()
    setCropper(undefined)
  }

  onCleanup(() => {
    destroyCropper()
  })

  return {
    cropper,
    initCropper,
    destroyCropper,
  }
}
